Repository openshift/installer-aro, pull requests merged in 2024-02, with the labels that each got.

#19 [4.14] Cherry-pick: CARRY: Do not run platform validation on an ARO cluster, it is perfor…
  pkg/asset/installconfig/installconfig.go
Labels: lgtm, approved

#16 [4.12] Update OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: lgtm

#18 [4.13] Update OWNERS files for Feb24
  OWNERS
  OWNERS_ALIASES
Labels: approved

#17 Update OWNERS files for Feb24
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved
